name: Dependencies

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cargo-deny:
    name: Bans, Licenses, Sources, Advisories
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
